### ISSUE TITLE
Could you please rebase or delete?

### ISSUE THREAD

**Issue by sachac** [sachac/.emacs.d#11]
Sorry, I messed up. @robertsgareth, @xashes, @peterpolidoro, @hobbes38111, @jonathan-willis, @keremvatandas, @KrokodileGlue, and @mik-d, could you please rebase or delete your forks? =|

**Comment by hobbes38111** [comment]
taken care of :)

**Comment by xashes** [comment]
I've rebased it :)

**Comment by sachac** [comment]
@hobbes38111 , @xashes : Thanks! Github Support took care of the rest. =)
