### ISSUE TITLE
how do *you* upgrade org-mode?

### ISSUE THREAD

**Issue by TomRoche** [sachac/.emacs.d#6]
This is a somewhat unusual issue, since I'm not yet an actual user. But it seems like a legitimate concern (YMMV), and I don't know of a better channel to raise it (feel free to point me elsewhere), so here goes: 3 questions about upgrading Org from [your Emacs configuration](https://github.com/sachac/.emacs.d).

I'm looking to adopt a new Emacs configuration (for complicated reasons that I'm still writing out) and yours is one I'm considering. I like the idea of using Org to literate-program Emacs-config files (et lots cetera), as you do. Accordingly another public Emacs configuration at which I'm looking is [Eric Schulte's Emacs Starter Kit](https://eschulte.github.io/emacs24-starter-kit/), which also keeps its config in `.org` files. Given his reliance on Org, I noticed this [open issue on ESK](https://github.com/eschulte/emacs24-starter-kit/issues/85).

The problem appears to be (as described in more detail in [this link](http://tonyballantyne.com/tech/elpa-org-mode-and-invalid-function-org-with-silent-modifications/) from the above issue), one can't update Org when it's in use ... which is obviously problematic if one's Emacs config, and therefore Emacs session, depends fundamentally on Org. So my questions are

1. Is this an obsolete problem? The ESK issue is almost a year old now (Nov 2015), and the [article to which it points](http://tonyballantyne.com/tech/elpa-org-mode-and-invalid-function-org-with-silent-modifications/) is almost 2 years old. So perhaps this problem has just gone away? If not, ...

2. Is this not a problem for your config? I notice ESK has a normal elisp `init.el` stub which uses `org-babel-load-file` to load the rest of his configuration, so an ESK-configured Emacs session is _always_ running Org. By contrast, you are using Org offline to write your config to a `Sacha.el`, which is the target for the symlink that is _your_ `init.el`.

That being said, (a) I'm guessing that this problem has not gone away, and (b) I notice that you start running Org fairly soon (relatively speaking--you have one seriously BFIS**[1]** :-) If so, I'd like to know,

3. How do you update Org? I'm guessing long-time `org-mode`rs keep some alternate configuration or `emacs -q` one-liner available for this purpose, but since I'm not yet assimilated into the Org I really don't know.

**[1]**: big f`@#$%^&` init script

**Comment by sachac** [comment]
It's only about 5k lines as an .el. ;)

As for Org updating, since I've got a git checkout of it, all I need to do is git pull and make. I suppose I could go back to using the package system for that as well, but since I have the Git checkout anyway, I might as well take advantage of it. =)
