### ISSUE TITLE
add readme, point to http://pages.sachachua.com/.emacs.d/Sacha.html

### ISSUE THREAD

**Issue by TomRoche** [sachac/.emacs.d#7]
I'm looking to adopt a new Emacs configuration (for complicated reasons that I'm still writing out) and yours is one I'm considering. Basically I'm looking at various public `.emacs.d` to see how they're assembled, what functionality they bring in "for free" (to adopters), how active they are, etc. I kinda like [yours](https://github.com/sachac/.emacs.d), but was getting frustrated browsing [Sacha.org](https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.org) because
1. It's one seriously big &lt;bleep/>ing init script! "Monolithic" like Stone-&lt;bleep>ing-henge !-)
2. It has no table of contents, making it very hard to browse for functionality, etc.
3. I thought, "NP, [Sacha.html](https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.html) will surely have a TOC." And it does, as I notice in line#=239 ... but only because GitHub insists on showing HTML! (but with syntax highlighting! that sure makes it more readable :-)

Eventually I noticed I was in branch=`gh-pages`, dopeslapped myself, and found my way to http://pages.sachachua.com/.emacs.d/Sacha.html . But perhaps you could make a `readme.org` for your project, and add text pointing to that page? That should prevent slow folks like me from wasting time, and even slower folks (or at least, folks with less GH experience) from just giving up.

**Comment by sachac** [comment]
Added! I had a link to the HTML version in the preface (with a friendly URL and everything! http://sach.ac/dotemacs , which is also http://sachachua.com/dotemacs) , but a README makes it more obvious. And yeah, I should point out that the published version has a TOC and other nice things...

**Comment by sachac** [comment]
Mmm, I should probably add an index.html for good measure, too. =)
