### ISSUE TITLE
A possible typo?

### ISSUE THREAD

**Issue by QikeLi** [sachac/.emacs.d#9]
Thanks for your beautifully written configuration! I wonder if there is a typo in the second line from the bottom of this excerpt (see following). Is the letter 't' not supposed to be outside of the parentheses? Thank you!

    (setq org-agenda-files
          (delq nil
                (mapcar (lambda (x) (and (file-exists-p x) x))
                    '("~/personal/organizer.org"
                      "~/personal/sewing.org"
                      "~/personal/people.org"
                      "~/Dropbox/wsmef/trip.txt"
                      "~/personal/business.org"
                      "~/personal/calendar.org"
                      "~/Dropbox/wsmef/puppy.txt"
                      "~/Dropbox/tasker/summary.txt"
                      "~/Dropbox/public/sharing/index.org"
                      "~/dropbox/public/sharing/learning.org"
                      "~/code/emacs-notes/tasks.org"
                      "~/sachac.github.io/evil-plans/index.org"
                      "~/personal/cooking.org"
                      "~/personal/routines.org"))))t
    (add-to-list 'auto-mode-alist '("\\.txt$" . org-mode))

**Comment by sachac** [comment]
Yes, whoops! Fixed. Thanks!
